CREATE TABLE `courses` (
	`id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`name` VARCHAR(20) NOT NULL,
	`image` VARCHAR(225) NOT NULL
);

CREATE TABLE `topics` (
	`id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`title` VARCHAR(50) NOT NULL,
	`body` TEXT NOT NULL,
	`course_id` INT UNSIGNED NOT NULL
);